### ISSUE TITLE
Contradictory Default

### ISSUE THREAD

**Issue by IanVS** [bmildren/percona_mysql#4]
In https://github.com/bmildren/percona_mysql/blob/master/defaults/main.yml#L17-L22 the default is set to false, but the comment says that to override the default, set it to false.  I'm confused whether by default it will upgrade...

**Comment by bmildren** [comment]
Thanks this has been updated.  This is used here: https://github.com/bmildren/percona_mysql/blob/master/tasks/configuration_pre_install.yml
- name: check if we're installing or upgrading (default is install)  
  set_fact:  
    percona_mysql_state='latest'  
  when: percona_mysql_upgrade

Essentially by default we just want to ensure the package is installed, and we don't want to upgrade to latest  unless we explicitly set percona_mysql_upgrade to true.
