### ISSUE TITLE
innodb buffer pool size

### ISSUE THREAD

**Issue by stevetoldme** [bmildren/percona_mysql#5]
Curious to why you use 25% of system memory for buffer pool. 
"{{ ( ansible_memtotal_mb / 4 ) | int }}"

I typically use 80% (since its dedicated mysql) and use:
{{ (ansible_memtotal_mb \* 0.8) | int }}M

I am super new to Ansible. Thank you for the awesome role.

**Comment by bmildren** [comment]
Hi, thanks for the feedback!  The thinking here is not everyone runs MySQL on a dedicated host, so setting the innodb buffer pool at 25% of the system ram, was just to have a safe and reasonable default for the public distribution of this role.  The calculation can be amended, or the variable can be overridden, and it's recommended it is if you use this in production.
