### ISSUE TITLE
Task "remove superfluous root users" problem

### ISSUE THREAD

**Issue by KIVagant** [bmildren/percona_mysql#7]
Hello.

I found strange trouble with this role installation on different centos7 instances. First time I found this trouble when I tried to install it on vagrant "centos/7" default box. It's strange, but on different boxes I saw different results. At all, I tried to run this role on several boxes: "centos/7", "hfm4/centos7", "jayunit100/centos7" and "geerlingguy/centos7". And just on part of them I gived this error:

```
TASK: [ben.mildren.percona_mysql | ensure percona database exists] ************
<192.168.99.100> REMOTE_MODULE mysql_db name=percona state=present login_unix_socket=/var/run/mysqld/mysqld.sock
failed: [192.168.99.100] => {"failed": true}
msg: unable to connect, check login credentials (login_user, and login_password, which can be defined in ~/.my.cnf), check that mysql socket exists and mysql server is running
FATAL: all hosts have already failed -- aborting
```

After that message, when I tried to run `mysql -S /var/run/mysqld/mysqld.sock` in guest machine shell, I saw this: `Access denied for user 'root'@'localhost' (using password: NO)`

This behaviour does not depends on percona_mysql_root_password variable, but eventually I found a decision. When I comment "remove superfluous root users" task, this problem was disappear.

I don't sure, that I can correctly fix the problem in this role. For me, I added the condition: `when: remove_superfluous_root_users == true` under task (and relevant variable to defaults vars).

But maybe, you can make more clever fix?

**Comment by pinepain** [comment]
In fact, it works as expected. 

To get things run without slashing the code, just add `become: true` (or `sudo: true` for ansible < 1.9) to your inventory file (assume become_user is default and not overridden anywhere in configs and/or cli).

Here is short explanation:

`secure_installation.yml` run results in `root` access from `localhost` only and set password to `root` (preset or randomly generated). And here is the moment that may be not very obvious at first glance - root credentials are written in `/root/.my.cnf`, and mysql loads `~/.my.cnf` on start. But when you become root with `sudo` or `sudo -s`, your `$HOME` points to regular user home dir, not root. If you try with `sudo -i` you'll get fresh shell (-i runs the login shell specified for target user, so in short it is close to full login process with loading login-specific files like .profile or so).

During provisioning, specifying `become: true` for tasks that requires mysql root login (via `login_unix_socket=/var/run/mysqld/mysqld.sock`) should fix the problem.

Also note, that `percona_mysql_installation_user` user also get it user-specific `.my.cnf` with `percona_mysql_user_name` user, which is set to `vagrant` by default, see `templates/user.my.cnf.j2` for details.
